I = "TAATAGATGGGCGGGCAACCTCTAAATGTACAATTGATGATTAGCGAGGGGATTGTACCCAACCAGCCATTGAATACGAATATGGCCGCAACCCTGCGGGCGCCTTCTAATGGGACAAATCGCTTTTCGATGTATTAGCGATCTGGTTGTGTAGTGCGAGAAGGGAGCTACACATTGATTTCGCTCGCTGTGTCCGTTCACGGTCGAACCCGATGCACCAAGCAAATCCCCTCGACATGAAATTAGTCAGGCAGCAGCGCCGGTCTCCGCAGGAAGGCGTCTTAAGCAGAACGGCGTATAAATTGGTAGCACGAACACGCTTGCTTCGCTCACCAATACGTAGAACTGATGAACTGAATTGATAATGACATTGGCTATGTCCGTAAACTCCGATCGAAATCTATTCGCAATGGAGAAAAGAGTATCCGTGGAACCATACATCACGTTGCCACTACAAGGGGTTTCGTCGCCGGCTTGACGAGGACGTTGAACATTATCGTTTGTCGGCACTGCTAACATGATCTCACGTTCTGAATGGACTCATTGAAAAACGGGTCTAACACCCCTGTTGTGTCCAGAGACTTCAACACCTATGACTCGTAACGAGTCATTGGGTAAGAGCAGACCTGCAATGCGACACGTATGGCATTCGCCAACGCAGATCAGTTCTATAAAGTAAACCTAGCCCGAATATTCCAGAAAGGCGCGAGCCGGATGGGTTTTCGCTTAAAGGAGGCACCGGTGTCGAGTCAAGGGGGTCAGATTTTCGTTGAACGGCAAGAGGGTAACAAACGCGATACCTTAAGTCCTTTTTAAAGTCGGGAGATGGACTATTCATAC"


A = 0
T = 0
C = 0
G = 0

for x in I:
    if x == "A":
        A += 1
    if x == "T":
        T += 1
    if x == "C":
        C += 1
    if x == "G":
        G += 1

print(A, C, G, T)
