DNA_seq = "AACTATCTGATGACAACTGTCAAAGGTGTCTAAAAGACGTGTACCTGTAGTTCCAGTGGGACCGGTATCACGAGATGTCTGATGCTAGTCGAATAGAGGCATTATATAAAGTATCAATCCATCAGGTAAGTATGTGGGTAGTAGCATAATTTGTAATGAATTCCCGGACTAGATAGCTGAAGGCAGGTTCTTACCAAATCGTGGGACAAGGTGCCACGAACAACGAGCCCCACTTCCGCGACGAAAAAAGGAGTCTGGGCTCCCTGCCTGCTGCAAACAACTTGCCTCGAATCCGCGTTAATACCAATGTGAGTGGACAGATCACTCATCTTAGCCTGCCGTTCATGTCTATTGCACCCTAGGAAAGGCAAACTGAAGGGCTCCACGCTGCCGCGAGTGGACTTCGGACCATGCATAAAAGATCTGGATACCGGGATGCATGCAACTTTTCGTTCACCATTGAGTATGTCATACTAGTGAACGACGATCAGTAACAAATCCCCCACGCGACCTAGACACGCAAACCTTCTAGGACGGCTTCTTTGAGGGTTTCTATTGTGGGGCATAGCCACGGGGATGAGGTGGACGGAAAGCCACTATGGCAATCTATGGGAGAATCCCTGCGGGCATTCACGAGATTTGTCGTGTACCCCTCACACTACGCCAGCCCAGTGGCACATCTTATTTATTTAAATCGACTGATATTAACCGGTGATTTGACTGTGCCTGGCCCAGCAAGCACCTTGTTCGAGTCTAGGTCTCAACCCAACGCCCCGAACTCGGTGTGGAGCGCTCTCTTCGAAAAAATCCGATTCCTGGCCAGTCCTACCCTGGAGCTACAATCGCTATAGGCACGGTTCGTATCTAGGAACGGAGTAAGGTACTCAGGAGAATACGTGAATCAGGTAGCTTGCCCGGCGACCTGAGCCATGAATCTAAAAGGTTGGCATTTTAAG"
RNA_seq = ""
for base in DNA_seq:
    if base == "A":
        RNA_seq += "A"
    if base == "T":
        RNA_seq += "U"
    if base == "C":
        RNA_seq += "C"
    if base == "G":
        RNA_seq += "G"

print(RNA_seq)
