DNA_seq = "CGTACCTCCCTTGTCCATTGTTCGTAATCCTAATGACCATATGCAGCGTTCCACCATTTCATAATCTTCCATTCAAGTATCGGACTCACCGTCTTGATATTGGTACGTACATTCTGGGTCAGGAAGGCGCACCGTGTGCATCACGGCCTGGACGTTACCCATCCGCAATGGATTTCAAGAAACAATTCCCGCTCATATGCGTGGTACTGCTTTGGCAGAACAGACGAGTATCGCGTCCGTGCCAACCGTCACTTTGCAAATAGGAAGCCTGCCTACTGTGTAGGCGAATCAGAACCCACCATTAGCAGCCTCTTGGACAACGGTAGGCGACGAATGTATGTACTGTGGATTTCACGGGGCACCTAGTCAATGGGACATTGTGATGTCTGAATCTTCCGACTTAGGCGGTCGGCTTGAAGTCTTCAGGTAGTTTCGAGTCCGTTGCAAGAGGAGAGGGCAGCGTACTGAATTACAACGGGCAGGATCAATTACCAGCATAGTCTCCTATAGTTATTTTAACGTGAAAGTGCAGTCGCAAAGAAGTACTGTTGGGTGCAGGGCTATGCTTGTTAGGGATCTGATACTGGGCCCTTGCGGGTTCTTTACGATCATTAGGCTACAAAGCCCTTGCGTTTCAACTGTCAACGAAGGGCTGTTCGAGTGGGGTAGAATGCTGAGCATCACCGGGAAACCATGTTAGCTTAGTGTGCCCATTACTGTATTTGGGCGATGTAGCCTTATTACCAAGATGCTGATATGCACAAAACCATGACCACGCGTATACGCATTAGTCAAGCAACCTCAGCACAGTGCCCGTGTGTTTGACATCTCCGCCTTCAGGTTGGTTTAGCTAGCGTGAAAACTGTTGAGTGGCTAAAAGTAACGGTTATGGAGAGGTCAAAGGTGGTGCTCACCATGACGGGGACAACGGAGAGGTATGCGTAAAGGGGTACTCCGTACCCAACAGGATTCGGATTATGGGAACGGCGCAC"
rev_DNA_seq = ""
rev_com = ""

for base in reversed(DNA_seq):
    rev_DNA_seq += base

for b in rev_DNA_seq:
    if b == "A":
        rev_com += "T"
    if b == "T":
        rev_com += "A"
    if b == "C":
        rev_com += "G"
    if b == "G":
        rev_com += "C"

print(rev_com)
